name: build-push-cheeseshop-image

on:
  push:
    branches:
      # Meant for NETxxyy-* tickets
      - feature/*
      # Meant for DEVOPS-* tickets
      - hotfix/*
  pull_request:
    types:
      - closed
      - synchronize
    branches:
      # Meant for running after PR merged on master
      - master

jobs:
  get-next-tag-version:
    runs-on: ubuntu-latest
    name: Get the next version of the tag
    outputs:
      next-tag: ${{ steps.get_next_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get the next version of the tag
        id: get_next_tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # DO NOT create Git tag. Just calculate new tag version.
          dry_run: true
          # Helps avoid duplicate Docker image tags when two branches are created from same master commit.
          append_to_pre_release_tag: ${{ format('{0}.{1}', github.actor, github.sha) }}
        
      - shell: bash
        run: |
          echo "Current Latest Tag: $tag"
          echo "Github ref: ${{ github.ref }}"
          echo "Pull Req Base Ref: ${{ github.event.pull_request.base.ref }}"
        env:
          tag: ${{ steps.get_next_tag.outputs.new_tag }}

  # This is the actual calling job that calls the reusable workflow - to push image into DockerDev-Enp Artifactory Repo.
  dockerdev-enp-push:
    if: ${{ always() && github.ref != 'master' }}
    needs: [ get-next-tag-version ]
    uses: varun-charan/reusable-workflows/.github/workflows/docker-build-push.yaml@master
    with:
      docker_registry: dockerdev-enp.bin.cloud.barco.com
      docker_repo: varun
      image_name: cheeseshop
      image_tag: ${{ needs.get-next-tag-version.outputs.next-tag }}
      build_directory: docker-cheeseshop
      maintainer: "varun.charan@barco.com"
    secrets:
      registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
  
  
  # This is the actual calling job that calls the reusable workflow - to push image into Docker-Enp Artifactory Repo.
  docker-enp-push:
    if: ${{ always() && github.ref == 'master' }}
    needs: [ get-next-tag-version ]
    uses: varun-charan/reusable-workflows/.github/workflows/docker-build-push.yaml@master
    with:
      docker_registry: docker-enp.bin.cloud.barco.com
      docker_repo: varun
      image_name: cheeseshop
      image_tag: ${{ needs.get-next-tag-version.outputs.next-tag }}
      build_directory: docker-cheeseshop
      maintainer: "varun.charan@barco.com"
    secrets:
      registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

  # # After a Docker image with the next version has been created, create a tag for the same in Git repo.
  create-next-tag-version:
    runs-on: ubuntu-latest
    needs: [ dockerdev-enp-push, docker-enp-push ]
    # if: ${{ always() && github.ref == 'master' && contains(join(needs.*.result, ','), 'success') }}
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Create the next version of the tag
    steps:
      - uses: actions/checkout@v2

      # - name: Create the next version of the tag
      #   id: create_next_tag
      #   uses: mathieudutour/github-tag-action@v6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create_next_tag.outputs.new_tag }}
          name: Release ${{ steps.create_next_tag.outputs.new_tag }}
          body: ${{ steps.create_next_tag.outputs.changelog }}