name: build-push-cheeseshop-image

on:
  push:
    branches:
      # Meant for NETxxyy-* tickets
      - feature/*
      # Meant for DEVOPS-* tickets
      - hotfix/*
  pull_request:
    types:
      - closed
      - synchronize
    branches:
      # Meant for running after PR merged on master
      - master
  # For manual trigger of job, if required. Avoids need to use dummy commits to initiate workflow.Applicable to master branch only since for it, source tag is picked from Git tags and not from Commit hash as is the case for dev branches.
  workflow_dispatch:

jobs:
  # This is the actual calling job that calls the reusable workflow - to push image into Docker Artifactory Repo.
  invoke-reusable:
    uses: varun-charan/reusable-workflows/.github/workflows/docker-build-push.yaml@master
    with:
      dockerdev_registry: ${{ secrets.DOCKERDEV_REPO }}
      docker_registry: ${{ secrets.DOCKER_REPO }}
      docker_repo: varun
      image_name: cheeseshop
      build_directory: docker-cheeseshop
      maintainer: "varun.charan"
    secrets:
      registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
