name: build-push-cheeseshop-image

on:
  push:
    branches:
      - feature/*
      - hotfix/*

jobs:
  github-run-number:
    runs-on: ubuntu-latest
    name: Provide GITHUB_RUN_NUMBER
    outputs:
      github-run-number: ${{ steps.github-run-number.outputs.github-run-number }}
    steps:
      - id: github-run-number
        run: |
          echo "::set-output name=github-run-number::$GITHUB_RUN_NUMBER"

  docker-dev:
    uses: ./.github/workflows/docker-build-push.yaml
    needs: [github-run-number]
    with:
      docker_registry: dockerdev-enp.bin.cloud.barco.com
      docker_repo: varun
      image_name: cheeseshop
      image_tag: ${{ steps.github-run-number.outputs.github-run-number }}
      build_directory: docker-cheeseshop
      maintainer: "varun.charan@barco.com"
    secrets:
      registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}