name: build-push-cheeseshop-image

on:
  push:
    branches:
      - feature/*
      - hotfix/*

env:
  DOCKER_REGISTRY: 
  DOCKER_REPO: varun
  IMAGE_NAME: cheeseshop
  IMAGE_VERSION: 1.0.0
  TARGET_DIRECTORY: docker-cheeseshop
  
jobs:
  docker-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: varun-charan/reusable-workflows/.github/workflows/docker-build-push.yaml@master
      with:
        docker_registry: dockerdev-enp.bin.cloud.barco.com
        docker_repo: varun
        image_name: cheeseshop
        image_tag: $GITHUB_RUN_NUMBER
        build_directory: docker-cheeseshop
        maintainer: "varun.charan@barco.com"
      secrets:
        registry_username: ${{ secrets.ARTIFACTORY_USERNAME }}
        registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}